spring.application.name=therapify
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/therapify}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:therapifyy@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:cjun rpbn uiio dmzg}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.port=${PORT:8080}