package com.example.therapify.enums;

public enum Specialty {
    PSICOLOGIA_CLINICA,
    TERAPIA_COGNITIVO_CONDUCTUAL,
    TERAPIA_DE_PAREJA,
    TERAPIA_FAMILIAR,
    PSIQUIATRIA,
    NEUROPSICOLOGIA,
    PSICOLOGIA_INFANTIL,
    PSICOLOGIA_LABORAL,
    SEXOLOGIA,
    TERAPIA_HUMANISTA
}
